name: Livriny
description: Application de livraison de nourriture avec GraphQL
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.0
  provider: ^6.0.0
  http: ^1.1.0
  intl: ^0.18.0
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.2.6
  
  # Optionnel pour les polylines
  flutter_polyline_points: ^3.1.0
  
  # Pour la gÃ©olocalisation
  geolocator: ^10.0.0
  
  # Pour les permissions
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
